const FZ={runtime:null,wellness:null,training:null,trends:null,system:null,page:'today',athleteCategory:'ALL',athleteRelationship:'ALL',trainingLens:'RESPONSE',trainingLimit:12,athleteLimit:12};
const $=id=>document.getElementById(id);
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const fmt=(v,d=0)=>num(v)===null?'—':Number(v).toLocaleString('en-ZA',{minimumFractionDigits:d,maximumFractionDigits:d});
const words=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const dateFmt=v=>{if(!v)return'—';const d=new Date(v.length===10?`${v}T12:00:00Z`:v);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('en-ZA',{timeZone:'Africa/Johannesburg',day:'2-digit',month:'short',year:'numeric'}).format(d)};
const timeFmt=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('en-ZA',{timeZone:'Africa/Johannesburg',hour:'2-digit',minute:'2-digit',hour12:false}).format(d)};
const stamp=v=>`${dateFmt(v)} · ${timeFmt(v)}`;
function pace(sec){if(num(sec)===null)return'—';const s=Math.round(Number(sec));return`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}/km`}
function statusTone(v=''){const s=String(v).toUpperCase();if(/PASS|STRONG|REAL POSITIVE|CONNECTED|CURRENT|MATCHED|GOOD|LIVE/.test(s))return'good';if(/STOP|ABORT|ERROR|LOW|NON_COMPARABLE|MISSING/.test(s))return'bad';return'warn'}

async function getJson(url,timeout=15000){const ctrl=new AbortController();const t=setTimeout(()=>ctrl.abort(),timeout);try{const r=await fetch(url,{cache:'no-store',signal:ctrl.signal});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return await r.json();}finally{clearTimeout(t)}}
function result(v){return v.status==='fulfilled'?v.value:null}
async function loadAll(){
  setShellState('SYNCING CANONICAL STATE');
  const [runtime,wellness,training,trends,system]=await Promise.allSettled([
    getJson('/api/runtime-state'),
    getJson('/api/wellness/today?refresh=0'),
    getJson('/api/training/memory?backDays=45&forwardDays=0'),
    getJson('/api/trends/current?days=45'),
    getJson('/api/system/status')
  ]);
  FZ.runtime=result(runtime);FZ.wellness=result(wellness);FZ.training=result(training);FZ.trends=result(trends);FZ.system=result(system);
  renderAll();
  setShellState('CANONICAL RUNTIME · LIVE WELLNESS · TRAINING MEMORY');
}

function setShellState(text){const el=$('stateStamp');if(el)el.textContent=text}
function renderDate(){const el=$('todayDate');if(el)el.textContent=new Intl.DateTimeFormat('en-ZA',{timeZone:'Africa/Johannesburg',weekday:'short',day:'2-digit',month:'long',year:'numeric'}).format(new Date())}
function nextRefresh(){const now=new Date();const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Johannesburg',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).formatToParts(now);const o=Object.fromEntries(parts.map(p=>[p.type,p.value]));const local=new Date(`${o.year}-${o.month}-${o.day}T${o.hour}:${o.minute}:${o.second}+02:00`);const slots=[6,20];let target=null;for(const h of slots){const d=new Date(local);d.setHours(h,0,0,0);if(d>local){target=d;break}}if(!target){target=new Date(local);target.setDate(target.getDate()+1);target.setHours(6,0,0,0)}return target}
function tickCountdown(){const el=$('countdown'),slot=$('nextSlot');if(!el)return;const t=nextRefresh();const ms=Math.max(0,t-Date.now());const sec=Math.floor(ms/1000);const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;el.textContent=`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;if(slot)slot.textContent=`Next scheduled intelligence state · ${String(t.getHours()).padStart(2,'0')}:00 SAST`}

function currentWellness(){return FZ.wellness?.wellness?.current||null}
function readiness(){return FZ.runtime?.renderContract?.readiness||null}
function currentTrainingFocus(){
  const sessions=(FZ.training?.sessions||[]).filter(s=>s.status!=='SUPERSEDED');
  const scored=sessions.map(s=>{const athlete=(s.events||[]).filter(e=>e.actor==='ATHLETE');let score=0;if(['STOPPED_EARLY','ABORTED','MODIFIED','SKIPPED'].includes(s.status))score+=50;if(athlete.length)score+=20;if(String(s.session_kind||'').includes('AET'))score+=8;score+=new Date(s.actual_start_at||s.planned_start_at||s.local_date).getTime()/1e14;return{s,score}}).sort((a,b)=>b.score-a.score);return scored[0]?.s||sessions.at(-1)||null
}

function renderToday(){
  const root=$('today');if(!root)return;const w=currentWellness();const r=readiness();const focus=currentTrainingFocus();
  const sourceAsOf=FZ.wellness?.wellness?.sourceAsOf;const liveState=FZ.wellness?.wellness?.freshness||'UNKNOWN';
  const rec=r?.primaryDecision||'Current recommendation is unavailable until the next validated intelligence state.';
  root.innerHTML=`
  <div class="fz-clean-hero">
    <div class="card score-card fz-clean-readiness"><div class="ring"><div class="score"><strong>${esc(r?.score??'—')}</strong><span>FZ Readiness</span></div></div><div class="hero-copy"><div class="tag"><i></i>${esc(r?.status||'STATE UNAVAILABLE')}</div><h2>${esc(r?.systemicRecovery||'Current systemic recovery state unavailable.')}</h2><p>${esc(r?.localTissueState||'No current local-function interpretation available.')}</p></div></div>
    <div class="card decision rich fz-clean-recommendation"><div class="eyebrow">CURRENT FZ RECOMMENDATION</div><h3>${esc(r?.status||'AWAITING STATE')}</h3><p>${esc(rec)}</p><div class="microline"><strong>Success condition:</strong> ${esc(r?.successCriteria||'Reassess when new athlete/source evidence arrives.')}</div></div>
  </div>
  <div class="section"><div class="section-head"><h2>Live Physiology</h2><p>${esc(liveState)} · Garmin source ${sourceAsOf?stamp(sourceAsOf):'—'} · operational store ${FZ.wellness?.wellness?.ingestedAt?stamp(FZ.wellness.wellness.ingestedAt):'—'}</p></div>
    <div class="fz-live-grid">
      ${metricCard('Steps',fmt(w?.steps),'today',w?.distanceKm!==undefined?`${fmt(w?.distanceKm,2)} km`:null)}
      ${metricCard('Body Battery',fmt(w?.bodyBattery),'today',w?`High ${fmt(w.bodyBatteryHigh)} · Low ${fmt(w.bodyBatteryLow)}`:null)}
      ${metricCard('Stress',fmt(w?.stress),'current',w?.stressAvg!==undefined?`Daily avg ${fmt(w?.stressAvg)}`:null)}
      ${metricCard('Heart rate',fmt(w?.heartRate),'bpm',w?.restingHeartRate!==undefined?`Resting ${fmt(w?.restingHeartRate)} bpm`:null)}
      ${metricCard('HRV',fmt(w?.hrv),'ms','Overnight anchor')}
      ${metricCard('Sleep',fmt(w?.sleepScore),'score',w?.sleepHours!==undefined?`${fmt(w?.sleepHours,2)} h`:null)}
      ${metricCard('Active kcal',fmt(w?.activeCalories),'today',w?.activeMinutes!==undefined?`${fmt(w?.activeMinutes,1)} active min`:null)}
      ${metricCard('Respiration',fmt(w?.respiration,1),'br/min','Latest positive reading')}
    </div>
  </div>
  <div class="section"><div class="section-head"><h2>Training State</h2><p>Canonical execution + Athlete Memory · not a source activity list</p></div>${focus?trainingFocusCard(focus):'<div class="card rich"><h3>No canonical training session in the current memory window.</h3></div>'}</div>`;
}
function metricCard(label,value,unit,note){return`<div class="card metric fz-live-metric"><div class="live-top"><span class="m-label">${esc(label)}</span><span class="live-state">LIVE</span></div><div class="m-value">${esc(value)}${unit==='bpm'?' <small>bpm</small>':''}</div><div class="m-note">${esc(note||unit||'')}</div></div>`}
function meaningCard(title,text){return`<div class="card rich"><div class="eyebrow">${esc(title)}</div><p>${esc(text)}</p></div>`}
function trainingFocusCard(s){const events=(s.events||[]).filter(e=>e.actor==='ATHLETE').sort((a,b)=>new Date(b.occurred_at)-new Date(a.occurred_at));return`<div class="card rich fz-training-focus"><div class="fz-focus-head"><div><div class="eyebrow">LAST KEY EXECUTION · ${esc(dateFmt(s.local_date))}</div><h3>${esc(s.title||s.sport_type||'Training')}</h3></div><span class="pill ${statusTone(s.status)}">${esc(words(s.status))}</span></div>${events[0]?`<p>${esc(events[0].summary)}</p>`:'<p class="muted">No athlete-response event is linked to this session.</p>'}<button class="fz-link-button" data-open-page="train">Open Training Memory →</button></div>`}

function renderTrends(){
  const root=$('trends');if(!root)return;const t=FZ.trends;if(!t?.ok){root.innerHTML=unavailable('Trends','The canonical Trends contract is unavailable.');return}
  const s=t.summaries||{};const latest=t.performance?.latestMatchedAet;const load=t.load||{};const quality=t.quality||{};
  root.innerHTML=`
  <div class="section"><div class="section-head"><h2>Longitudinal Signals</h2><p>One canonical contract · recovery → performance → exposure cost → athlete voice → trajectory</p></div><div class="fz-signal-grid">
    ${signalCard('Recovery',s.recovery)}${signalCard('Performance',s.performance)}${signalCard('Exposure Cost',s.exposure)}${signalCard('Trajectory',s.trajectory)}
  </div></div>
  <div class="section"><div class="section-head"><h2>Recovery Response</h2><p>Historical overnight anchors + current canonical wellness overlay</p></div><div class="two"><div class="card chart-card"><h3>HRV</h3><div class="chart-meta">Daily overnight HRV · gaps remain gaps</div><div class="fz-clean-chart" id="cleanHrvChart"></div></div><div class="card chart-card"><h3>Sleep Score</h3><div class="chart-meta">Daily sleep score · no synthetic interpolation</div><div class="fz-clean-chart" id="cleanSleepChart"></div></div></div></div>
  <div class="section"><div class="section-head"><h2>Exposure Cost</h2><p>NCL is exposure context, not a performance score</p></div><div class="card chart-card"><div class="fz-chart-title-row"><div><h3>Normalised Cardio Load</h3><div class="chart-meta">${esc(load.formula)} · missing detail is never plotted as zero</div></div><div class="fz-rollup"><b>7d ${load.rolling7d?.value===null?'pending':fmt(load.rolling7d?.value,2)}</b><span>28d ${load.rolling28d?.value===null?'pending':fmt(load.rolling28d?.value,2)}</span></div></div><div class="fz-clean-chart" id="cleanNclChart"></div></div>${quality.loadMissingDates?.length?`<div class="fz-quality-note warn"><b>Data-quality gate</b><span>${quality.loadMissingDates.length} day(s) are waiting for HR-zone detail. They are gaps, not zero-load days.</span></div>`:''}</div>
  <div class="section"><div class="section-head"><h2>Performance Trajectory</h2><p>Matched AET is the standardized diagnostic; unlike runs remain contextual</p></div><div class="kpi-row">${latest?`<div class="kpi"><small>Latest matched P/HR</small><b>${fmt(latest.powerHr,3)}</b><span>${esc(dateFmt(latest.date))}</span></div><div class="kpi"><small>Power</small><b>${fmt(latest.avgPower)} W</b><span>matched AET</span></div><div class="kpi"><small>HR</small><b>${fmt(latest.avgHeartRate)} bpm</b><span>matched AET</span></div><div class="kpi"><small>Pace</small><b>${esc(pace(latest.paceSecPerKm))}</b><span>whole-session avg</span></div>`:'<div class="kpi"><small>Matched AET</small><b>Pending</b><span>Canonical data incomplete</span></div>'}</div>
    <div class="two" style="margin-top:12px"><div class="card chart-card"><h3>Matched Run AET · Power/HR</h3><div class="chart-meta">Matched + matched-with-caveat only · excluded attempts shown separately</div><div class="fz-clean-chart" id="cleanAetChart"></div></div><div class="card chart-card"><h3>Running Relationship Map</h3><div class="chart-meta">Dynamic canonical running exposures · power vs pace · comparison class retained</div><div class="fz-clean-chart" id="cleanRunScatter"></div></div></div>
    ${renderExcludedAet(t.performance?.excludedAet||[])}
  </div>
  <div class="section" id="trendAthleteVoice"><div class="section-head"><h2>Athlete Voice</h2><p>Derived from canonical Athlete Memory · no second subjective-history store</p></div>${renderVoiceSummary()}</div>
  <div class="section"><div class="section-head"><h2>Trajectory & Measurement Gaps</h2><p>Evidence strength, not fabricated progress percentages</p></div><div class="cap-grid fz-clean-cap-grid">${(t.capabilities||[]).map(capabilityCard).join('')}</div></div>
  <div class="section"><div class="fz-provenance-strip"><b>Runtime truth</b><span>${esc(t.provenance?.operationalTruth)}</span><b>Historical wellness seed</b><span>${esc(t.provenance?.historicalWellnessSeed||'—')}</span><b>Drive role</b><span>${esc(t.provenance?.auditRepresentation)}</span></div></div>`;
  queueMicrotask(mountTrendCharts);
}
function signalCard(name,text){return`<div class="card rich fz-signal-card"><div class="eyebrow">${esc(name)}</div><p>${esc(text||'No current interpretation available.')}</p></div>`}
function renderExcludedAet(rows){if(!rows.length)return'';return`<div class="card rich fz-excluded"><div class="eyebrow">NON-COMPARABLE / EXCLUDED AET EXPOSURE</div>${rows.slice(-4).map(r=>`<div class="fz-excluded-row"><b>${esc(dateFmt(r.date))} · ${esc(r.title||'AET')}</b><span>${esc(words(r.comparison))} · ${r.durationMin!==null?`${fmt(r.durationMin,1)} min`:''}${r.powerHr!==null?` · P/HR ${fmt(r.powerHr,3)}`:''}</span></div>`).join('')}<p>Excluded from the matched progression line, retained as training/tolerance evidence.</p></div>`}
function capabilityCard(c){return`<div class="cap"><div class="cap-head"><span class="cap-name">${esc(c.name)}</span><span class="cap-pri">${esc(c.priority)}</span></div><div class="cap-status ${statusTone(c.status)}">${esc(c.status)}</div><div class="evidence">${esc(c.evidence)} evidence</div><p>${esc(c.summary)}</p><small>Next validation · ${esc(c.next)}</small></div>`}

function athleteRows(){const p=FZ.training||{};const sessions=(p.sessions||[]).filter(s=>s.status!=='SUPERSEDED');const map=new Map(sessions.map(s=>[s.session_id,s]));const out=[],seen=new Set();for(const s of sessions){for(const e of s.events||[]){if(e.actor!=='ATHLETE')continue;const k=e.event_key||e.event_id;if(seen.has(k))continue;seen.add(k);out.push({...e,linkedSession:s});}}for(const e of p.contextEvents||[]){if(e.actor!=='ATHLETE')continue;const k=e.event_key||e.event_id;if(seen.has(k))continue;seen.add(k);out.push({...e,linkedSession:e.session_id?map.get(e.session_id)||null:null});}return out.sort((a,b)=>new Date(b.occurred_at)-new Date(a.occurred_at))}
function categories(e){const supplied=Array.isArray(e?.payload?.memoryCategories)?e.payload.memoryCategories.map(x=>String(x).toUpperCase()):[];if(supplied.length)return supplied;const out=[];const text=`${e.summary||''} ${e.event_type||''}`.toLowerCase();if(/fresh|energy|headspace|readiness|legs|sleep/.test(text))out.push('STATE');if(/session|workout|run|aet|training|stopped/.test(text))out.push('SESSION');if(/hard|tough|fatigue|doms|sore|pain|cramp|limiter/.test(text))out.push('COST');if(/recover|fresh|next.day|48h/.test(text))out.push('RECOVERY');if(/carb|banana|fuel|food|hunger|hydration/.test(text))out.push('FUELING');if(/hand|finger|hamstring|knee|throat|stomach|gi|pain|symptom/.test(text))out.push('CONSTRAINT');if(e.certainty==='HYPOTHESIS')out.push('HYPOTHESIS');return [...new Set(out.length?out:['STATE'])]}
function athleteEventStamp(e){if(e?.payload?.timestampPrecision==='date-only'||e?.payload?.exactTimeRetained===false)return`${dateFmt(e.occurred_at)} · TIME NOT RETAINED`;return stamp(e.occurred_at)}
function athleteCard(e){const cats=categories(e),s=e.linkedSession;return`<article class="fz-athlete-memory-event"><div class="fz-athlete-memory-top"><time>${esc(athleteEventStamp(e))}</time><span>${esc(e.certainty==='REPORTED'?'ATHLETE REPORTED':words(e.certainty))}</span></div><div class="fz-athlete-memory-cats">${cats.map(c=>`<b>${esc(c)}</b>`).join('')}</div><p>${esc(e.summary||words(e.event_type))}</p><div class="fz-athlete-memory-link"><small>${s?'LINKED TRAINING':'RELATIONSHIP'}</small><strong>${esc(s?`${s.title||s.sport_type||'Training'} · ${dateFmt(s.local_date)}`:'No linked session')}</strong><span>${esc(s?`${words(s.status)} · canonical session`:'Valid athlete context retained independently of a workout.')}</span></div></article>`}
function renderVoiceSummary(){const rows=athleteRows();if(!rows.length)return'<div class="card rich">No Athlete Memory observations available.</div>';const counts=['STATE','SESSION','COST','RECOVERY','FUELING','CONSTRAINT','HYPOTHESIS'].map(c=>[c,rows.filter(r=>categories(r).includes(c)).length]).filter(x=>x[1]);return`<div class="fz-athlete-voice-bridge"><div class="fz-athlete-voice-counts">${counts.map(([c,n])=>`<span><b>${n}</b> ${c}</span>`).join('')}</div><button class="fz-link-button" data-open-page="train" data-scroll-athlete="1">Open full Athlete Memory →</button></div><div class="fz-athlete-voice-recent">${rows.slice(0,4).map(athleteCard).join('')}</div>`}

function renderTrain(){
  const root=$('train');if(!root)return;const p=FZ.training;if(!p?.ok){root.innerHTML=unavailable('Training Memory','The canonical training ledger is unavailable.');return}
  const rows=athleteRows();const cats=['ALL','STATE','SESSION','COST','RECOVERY','FUELING','CONSTRAINT','HYPOTHESIS'];const rels=[['ALL','All relationships'],['LINKED','Linked to training'],['STANDALONE','Standalone']];const filtered=rows.filter(r=>(FZ.athleteCategory==='ALL'||categories(r).includes(FZ.athleteCategory))&&(FZ.athleteRelationship==='ALL'||(FZ.athleteRelationship==='LINKED'?!!r.linkedSession:!r.linkedSession)));const sessions=trainingSessions();
  root.innerHTML=`<div class="section" id="athleteMemory"><div class="section-head"><h2>Athlete Memory</h2><p>Canonical subjective evidence · observation date/time stays separate from any linked training date</p></div><div class="fz-athlete-memory-shell"><div class="fz-athlete-memory-head"><div><div class="eyebrow">ATHLETE MEMORY · CANONICAL</div><strong>What you reported, when you reported it, and what it related to</strong></div><div class="fz-athlete-memory-stats"><span><b>${rows.length}</b> observations</span><span><b>${rows.filter(r=>r.linkedSession).length}</b> training-linked</span><span><b>${rows.filter(r=>!r.linkedSession).length}</b> standalone</span></div></div><div class="fz-athlete-memory-filters">${cats.map(c=>`<button data-athlete-category="${c}" class="${FZ.athleteCategory===c?'active':''}"><span>${c}</span><b>${c==='ALL'?rows.length:rows.filter(r=>categories(r).includes(c)).length}</b></button>`).join('')}</div><div class="fz-athlete-memory-relationship">${rels.map(([k,l])=>`<button data-athlete-relationship="${k}" class="${FZ.athleteRelationship===k?'active':''}">${l}</button>`).join('')}<span>Showing ${Math.min(filtered.length,FZ.athleteLimit)} of ${filtered.length}</span></div><div class="fz-athlete-memory-list">${filtered.slice(0,FZ.athleteLimit).map(athleteCard).join('')||'<div class="fz-empty">No Athlete Memory entries match these filters.</div>'}</div>${filtered.length>FZ.athleteLimit?'<button class="fz-more" data-athlete-more>Show more</button>':''}</div></div>
  <div class="section"><div class="section-head"><h2>Training Memory</h2><p>One canonical execution history · Garmin + Tredict retained as evidence, not duplicate workouts</p></div><div class="fz-training-lenses">${[['RESPONSE','Response memory'],['CHANGED','Changed / stopped'],['AET','AET'],['RUNNING','Running'],['ALL','All sessions']].map(([k,l])=>`<button data-training-lens="${k}" class="${FZ.trainingLens===k?'active':''}">${l}</button>`).join('')}</div><div class="fz-training-list">${sessions.slice(0,FZ.trainingLimit).map(trainingCard).join('')||'<div class="fz-empty">No sessions match this lens.</div>'}</div>${sessions.length>FZ.trainingLimit?'<button class="fz-more" data-training-more>Show more</button>':''}</div>`;
}
function trainingSessions(){const all=(FZ.training?.sessions||[]).filter(s=>s.status!=='SUPERSEDED').sort((a,b)=>new Date(b.actual_start_at||b.planned_start_at||b.local_date)-new Date(a.actual_start_at||a.planned_start_at||a.local_date));if(FZ.trainingLens==='ALL')return all;if(FZ.trainingLens==='AET')return all.filter(s=>s.session_kind==='AET'||/aet/i.test(s.title||''));if(FZ.trainingLens==='RUNNING')return all.filter(s=>String(s.sport_type||'').toLowerCase().includes('run'));if(FZ.trainingLens==='CHANGED')return all.filter(s=>['STOPPED_EARLY','ABORTED','MODIFIED','SKIPPED'].includes(s.status));return all.filter(s=>['STOPPED_EARLY','ABORTED','MODIFIED','SKIPPED'].includes(s.status)||(s.events||[]).some(e=>e.actor==='ATHLETE'))}
function trainingCard(s){const ae=(s.events||[]).filter(e=>e.actor==='ATHLETE').sort((a,b)=>new Date(a.occurred_at)-new Date(b.occurred_at));const sources=[...new Set((s.sources||[]).map(x=>x.source_key).filter(Boolean))];return`<article class="card rich fz-training-card"><div class="fz-focus-head"><div><div class="eyebrow">${esc(dateFmt(s.local_date))}${s.actual_start_at?` · ${esc(timeFmt(s.actual_start_at))}`:''}</div><h3>${esc(s.title||s.sport_type||'Training')}</h3></div><span class="pill ${statusTone(s.status)}">${esc(words(s.status))}</span></div><div class="fz-training-meta"><span>${esc(words(s.sport_type))}</span>${s.session_kind?`<span>${esc(words(s.session_kind))}</span>`:''}<span>${esc(sources.join(' + ')||'canonical')}</span></div>${ae.length?`<div class="fz-session-events">${ae.map(e=>`<div><b>${esc(athleteEventStamp(e))}</b><p>${esc(e.summary)}</p></div>`).join('')}</div>`:'<p class="muted">No athlete-response event linked.</p>'}</article>`}

function renderSystem(){const root=$('system');if(!root)return;const s=FZ.system;if(!s?.ok){root.innerHTML=unavailable('System','System health is unavailable.');return}const r=s.runtime||{};const garmin=s.garmin||{};const t=s.tredict||{};root.innerHTML=`
<div class="section"><div class="section-head"><h2>System Health</h2><p>Truth, freshness and provenance · implementation history removed</p></div><div class="status-grid"><div class="status-card"><small>Operational truth</small><b class="good">NEON</b><p>Canonical runtime, wellness, training and Athlete Memory.</p></div><div class="status-card"><small>Runtime state</small><b class="${r.masterValidated?'good':'warn'}">${r.masterValidated?'VALIDATED':'UNAVAILABLE'}</b><p>${esc(r.stateId||'—')} · master state ${esc(r.masterAsOf?stamp(r.masterAsOf):'—')}</p></div><div class="status-card"><small>Garmin / Fitness AI</small><b class="${statusTone(garmin.connection?.status)}">${esc(garmin.connection?.status||'UNKNOWN')}</b><p>Wellness source ${esc(garmin.latestWellness?.source_as_of?stamp(garmin.latestWellness.source_as_of):'—')}</p></div><div class="status-card"><small>Tredict</small><b class="${t.configured?'good':'warn'}">${t.configured?'CONNECTED':'NOT CONFIGURED'}</b><p>Executed training evidence ${esc(t.latestEvidence?.find(x=>x.record_type==='executed_activity')?.latest_date||'—')}</p></div></div></div>
<div class="section"><div class="section-head"><h2>Canonical Architecture</h2><p>Source evidence → operational truth → intelligence → PWA</p></div><div class="pipeline-flow"><div class="pipe"><small>Evidence</small><b>Garmin</b></div><div class="pipe"><small>Evidence</small><b>Tredict</b></div><div class="pipe"><small>Evidence</small><b>Athlete Memory</b></div><div class="pipe"><small>Operational truth</small><b>Neon</b></div><div class="pipe"><small>Intelligence</small><b>FZ state / recommendation</b></div><div class="pipe"><small>Presentation</small><b>PWA</b></div></div><div class="fz-quality-note"><b>Drive</b><span>Human-owned audit representation / flight recorder. It is not the runtime engine.</span></div></div>
<div class="section"><div class="section-head"><h2>Evidence Coverage</h2><p>What the runtime actually has</p></div><div class="truth-table"><div class="head">Source</div><div class="head">Type</div><div class="head">Coverage / freshness</div>${(s.trainingEvidence||[]).map(x=>`<div>${esc(x.source_key)}</div><div>${esc(words(x.record_type))}</div><div class="muted">${fmt(x.records)} records · ${esc(x.earliest_date||'—')} → ${esc(x.latest_date||'—')} · latest ingest ${esc(x.latest_ingest?stamp(x.latest_ingest):'—')}</div>`).join('')}<div>Athlete Memory</div><div>Subjective events</div><div class="muted">${fmt(s.athleteMemory?.events)} events · latest ${esc(s.athleteMemory?.latest_event?stamp(s.athleteMemory.latest_event):'—')}</div></div></div>
<div class="section"><div class="section-head"><h2>Product Boundaries</h2><p>Where information belongs after consolidation</p></div><div class="four"><div class="card rich"><div class="eyebrow">TODAY</div><p>Current state + current recommendation + current training state.</p></div><div class="card rich"><div class="eyebrow">TRENDS</div><p>Longitudinal change, response, performance, cost and trajectory.</p></div><div class="card rich"><div class="eyebrow">TRAIN</div><p>Canonical execution history + canonical Athlete Memory.</p></div><div class="card rich"><div class="eyebrow">SYSTEM</div><p>Source health, freshness, provenance and architecture.</p></div></div></div>`}

function unavailable(title,text){return`<div class="section"><div class="card rich"><div class="eyebrow">${esc(title)}</div><h3>Temporarily unavailable</h3><p>${esc(text)}</p></div></div>`}

function mountTrendCharts(){const t=FZ.trends;if(!t)return;lineChart('cleanHrvChart',(t.recovery?.wellnessHistory||[]).map(x=>({label:x.dateLabel||x.date,value:num(x.hrv),sub:x.status})),{unit:' ms'});lineChart('cleanSleepChart',(t.recovery?.wellnessHistory||[]).map(x=>({label:x.dateLabel||x.date,value:num(x.sleepScore),sub:x.status})),{unit:''});lineChart('cleanNclChart',(t.load?.series||[]).slice(-28).map(x=>({label:x.dateLabel,value:num(x.value),sub:x.state})),{unit:' NCL',zeroFloor:true});lineChart('cleanAetChart',(t.performance?.matchedAet||[]).map(x=>({label:x.date?dateFmt(x.date).replace(' 2026',''):x.dateLabel,value:num(x.powerHr),sub:x.comparison})),{unit:' P/HR'});scatterChart('cleanRunScatter',t.performance?.runningRelationship||[])}
function lineChart(id,points,{unit='',zeroFloor=false}={}){const el=$(id);if(!el)return;const valid=points.map((p,i)=>({...p,i})).filter(p=>p.value!==null);if(!valid.length){el.innerHTML='<div class="fz-empty">No valid points available.</div>';return}const W=720,H=210,P=26;let min=Math.min(...valid.map(p=>p.value)),max=Math.max(...valid.map(p=>p.value));if(zeroFloor)min=0;if(max===min){max+=1;min-=zeroFloor?0:1}const x=i=>P+(i/Math.max(1,points.length-1))*(W-P*2),y=v=>H-P-((v-min)/(max-min))*(H-P*2);const segs=[];let cur=[];points.forEach((p,i)=>{if(p.value===null){if(cur.length){segs.push(cur);cur=[]}}else cur.push([x(i),y(p.value)])});if(cur.length)segs.push(cur);const paths=segs.map(seg=>`<path d="${seg.map((q,j)=>`${j?'L':'M'}${q[0].toFixed(1)},${q[1].toFixed(1)}`).join(' ')}"/>`).join('');const dots=valid.map(p=>`<circle cx="${x(p.i)}" cy="${y(p.value)}" r="4" data-i="${p.i}"/>`).join('');el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img"><line class="axis" x1="${P}" y1="${H-P}" x2="${W-P}" y2="${H-P}"/>${paths}${dots}</svg><div class="fz-chart-tooltip"></div>`;installScrub(el,points,i=>`${points[i].label} · ${fmt(points[i].value,points[i].value<10?3:1)}${unit}${points[i].sub?` · ${words(points[i].sub)}`:''}`)}
function scatterChart(id,rows){const el=$(id);if(!el)return;const data=rows.filter(r=>num(r.avgPower)!==null&&num(r.paceSecPerKm)!==null);if(!data.length){el.innerHTML='<div class="fz-empty">No canonical running points available.</div>';return}const W=720,H=210,P=30;const xs=data.map(r=>r.avgPower),ys=data.map(r=>r.paceSecPerKm);let xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys);if(xmax===xmin)xmax++;if(ymax===ymin)ymax++;const x=v=>P+((v-xmin)/(xmax-xmin))*(W-P*2),y=v=>P+((v-ymin)/(ymax-ymin))*(H-P*2);el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img"><line class="axis" x1="${P}" y1="${H-P}" x2="${W-P}" y2="${H-P}"/>${data.map((r,i)=>`<circle class="scatter ${esc(r.comparisonClass)}" cx="${x(r.avgPower)}" cy="${y(r.paceSecPerKm)}" r="6" data-i="${i}"/>`).join('')}</svg><div class="fz-chart-tooltip"></div><div class="fz-chart-legend"><span>MATCHED AET</span><span>CONTEXTUAL RUN</span><span>NON-COMPARABLE</span></div>`;installScrub(el,data,i=>`${dateFmt(data[i].date)} · ${words(data[i].comparisonClass)} · ${fmt(data[i].avgPower)} W · ${pace(data[i].paceSecPerKm)}`)}
function installScrub(el,data,label){const tip=el.querySelector('.fz-chart-tooltip');const svg=el.querySelector('svg');if(!tip||!svg)return;const move=ev=>{const r=svg.getBoundingClientRect();const x=Math.max(0,Math.min(r.width,ev.clientX-r.left));const i=Math.round((x/r.width)*(data.length-1));const item=data[i];if(!item)return;tip.textContent=label(i);tip.style.display='block';tip.style.left=`${Math.max(8,Math.min(r.width-190,x))}px`;tip.style.top='8px'};svg.addEventListener('pointermove',move);svg.addEventListener('pointerdown',move);svg.addEventListener('pointerleave',()=>tip.style.display='none')}

function renderAll(){renderDate();renderToday();renderTrends();renderTrain();renderSystem();showPage(FZ.page)}
function showPage(page){FZ.page=page;document.querySelectorAll('.page').forEach(el=>el.classList.toggle('active',el.id===page));document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));window.scrollTo({top:0,behavior:'instant'})}
document.addEventListener('click',e=>{const page=e.target.closest('[data-page],[data-open-page]');if(page){const p=page.dataset.page||page.dataset.openPage;showPage(p);if(page.dataset.scrollAthlete)setTimeout(()=>$('athleteMemory')?.scrollIntoView({behavior:'smooth'}),80);return}const ac=e.target.closest('[data-athlete-category]');if(ac){FZ.athleteCategory=ac.dataset.athleteCategory;FZ.athleteLimit=12;renderTrain();return}const ar=e.target.closest('[data-athlete-relationship]');if(ar){FZ.athleteRelationship=ar.dataset.athleteRelationship;FZ.athleteLimit=12;renderTrain();return}if(e.target.closest('[data-athlete-more]')){FZ.athleteLimit+=12;renderTrain();return}const tl=e.target.closest('[data-training-lens]');if(tl){FZ.trainingLens=tl.dataset.trainingLens;FZ.trainingLimit=12;renderTrain();return}if(e.target.closest('[data-training-more]')){FZ.trainingLimit+=12;renderTrain()}});
window.addEventListener('focus',()=>loadAll());document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')loadAll()});window.addEventListener('online',()=>loadAll());
renderDate();tickCountdown();setInterval(tickCountdown,1000);loadAll();setInterval(()=>{if(document.visibilityState==='visible')loadAll()},300000);
